if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
#	add_definitions(-Wall -Wextra -Wpedantic -Wconversion -Wold-style-cast -Weffc++)
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic" )
	SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Wpedantic -Wconversion" )
	#add_definitions(-Wall -Wextra -Wpedantic -Wconversion -Wold-style-cast)
	if(SANITIZE)
	    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address -fsanitize=undefined" )
		SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address -fsanitize=undefined" )
	    #add_definitions(-fsanitize=address -fsanitize=undefined)
	    list( APPEND LIBRARIES asan ubsan )
	elseif(TSANITIZE)
	    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=thread" )
		SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=thread" )
		#add_definitions(-fsanitize=thread)
	    list( APPEND LIBRARIES tsan )
	endif()
endif()
